sudo: required
services:
  - docker
before_install:
  - docker build -t rishikant42/multi-docker-app -f ./client/Dockerfile.dev ./client

scripts:
  - docker -e CI=true run rishikant42/multi-docker-app npm test

after_success:
  - docker build -t rishikant42/multi-client ./client
  - docker build -t rishikant42/multi-nginx ./nginx
  - docker build -t rishikant42/multi-server ./server
  - docker build -t rishikant42/multi-worker ./worker

  # Login to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push rishikant42/multi-client
  - docker push rishikant42/multi-nginx
  - docker push rishikant42/multi-server
  - docker push rishikant42/multi-worker