sudo: required
services:
  - docker
before_install:
  - docker build -t rishikant42/multi-docker-app -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true rishikant42/multi-docker-app npm test

after_success:
  - docker build -t rishikant42/multi-client ./client
  - docker build -t rishikant42/multi-nginx ./nginx
  - docker build -t rishikant42/multi-server ./server
  - docker build -t rishikant42/multi-worker ./worker

  # Login to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push rishikant42/multi-client
  - docker push rishikant42/multi-nginx
  - docker push rishikant42/multi-server
  - docker push rishikant42/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-525123395903"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
